version: '2'
services:
  mysql:
    container_name: mysql
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASS: admin
    volumes:
      - 'mysql-volume:/var/lib/mysql'
    ports:
      - '3306:3306'
volumes:
  mysql-volume: null
